// Fallback database of popular/essential Warframe mods.
// Used when the external API is loading or unreachable.

export const fallbackMods = [
  {
    uniqueName: "/Lotus/Upgrades/Mods/Rifle/RifleDamageMod",
    name: "Serration",
    polarity: "madurai",
    rarity: "Uncommon",
    baseDrain: 4,
    fusionLimit: 10,
    type: "Rifle Mod",
    levelStats: [
      { stats: ["+15% Damage"] },
      { stats: ["+30% Damage"] },
      { stats: ["+45% Damage"] },
      { stats: ["+60% Damage"] },
      { stats: ["+75% Damage"] },
      { stats: ["+90% Damage"] },
      { stats: ["+105% Damage"] },
      { stats: ["+120% Damage"] },
      { stats: ["+135% Damage"] },
      { stats: ["+150% Damage"] },
      { stats: ["+165% Damage"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/SerrationMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Serration",
    drops: [{ location: "Grineer Elite Lancer", chance: 0.02 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Rifle/RifleMultishotMod",
    name: "Split Chamber",
    polarity: "madurai",
    rarity: "Rare",
    baseDrain: 10,
    fusionLimit: 5,
    type: "Rifle Mod",
    levelStats: [
      { stats: ["+15% Multishot"] },
      { stats: ["+30% Multishot"] },
      { stats: ["+45% Multishot"] },
      { stats: ["+60% Multishot"] },
      { stats: ["+75% Multishot"] },
      { stats: ["+90% Multishot"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/SplitChamberMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Split_Chamber",
    drops: [{ location: "Tier 3 Defense Rewards", chance: 0.0251 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Pistol/PistolDamageMod",
    name: "Hornet Strike",
    polarity: "madurai",
    rarity: "Uncommon",
    baseDrain: 4,
    fusionLimit: 10,
    type: "Secondary Mod",
    levelStats: [
      { stats: ["+20% Damage"] },
      { stats: ["+40% Damage"] },
      { stats: ["+60% Damage"] },
      { stats: ["+80% Damage"] },
      { stats: ["+100% Damage"] },
      { stats: ["+120% Damage"] },
      { stats: ["+140% Damage"] },
      { stats: ["+160% Damage"] },
      { stats: ["+180% Damage"] },
      { stats: ["+200% Damage"] },
      { stats: ["+220% Damage"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/HornetStrikeMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Hornet_Strike",
    drops: [{ location: "Grineer Heavy Gunner", chance: 0.05 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Pistol/PistolMultishotMod",
    name: "Barrel Diffusion",
    polarity: "madurai",
    rarity: "Rare",
    baseDrain: 6,
    fusionLimit: 5,
    type: "Secondary Mod",
    levelStats: [
      { stats: ["+20% Multishot"] },
      { stats: ["+40% Multishot"] },
      { stats: ["+60% Multishot"] },
      { stats: ["+80% Multishot"] },
      { stats: ["+100% Multishot"] },
      { stats: ["+120% Multishot"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/BarrelDiffusionMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Barrel_Diffusion",
    drops: [{ location: "Seeker", chance: 0.03 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Melee/MeleeDamageMod",
    name: "Pressure Point",
    polarity: "madurai",
    rarity: "Common",
    baseDrain: 4,
    fusionLimit: 5,
    type: "Melee Mod",
    levelStats: [
      { stats: ["+20% Melee Damage"] },
      { stats: ["+40% Melee Damage"] },
      { stats: ["+60% Melee Damage"] },
      { stats: ["+80% Melee Damage"] },
      { stats: ["+100% Melee Damage"] },
      { stats: ["+120% Melee Damage"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/PressurePointMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Pressure_Point",
    drops: [{ location: "Corrupted Lancer", chance: 0.1 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Warframe/AvatarPowerMaxMod",
    name: "Flow",
    polarity: "naramon",
    rarity: "Rare",
    baseDrain: 4,
    fusionLimit: 5,
    type: "Warframe Mod",
    levelStats: [
      { stats: ["+25% Energy Max"] },
      { stats: ["+50% Energy Max"] },
      { stats: ["+75% Energy Max"] },
      { stats: ["+100% Energy Max"] },
      { stats: ["+125% Energy Max"] },
      { stats: ["+150% Energy Max"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/FlowMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Flow",
    drops: [{ location: "Butcher", chance: 0.02 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Warframe/AvatarPowerEfficiencyMod",
    name: "Streamline",
    polarity: "naramon",
    rarity: "Rare",
    baseDrain: 4,
    fusionLimit: 5,
    type: "Warframe Mod",
    levelStats: [
      { stats: ["+5% Ability Efficiency"] },
      { stats: ["+10% Ability Efficiency"] },
      { stats: ["+15% Ability Efficiency"] },
      { stats: ["+20% Ability Efficiency"] },
      { stats: ["+25% Ability Efficiency"] },
      { stats: ["+30% Ability Efficiency"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/StreamlineMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Streamline",
    drops: [{ location: "Corrupted Crewman", chance: 0.02 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Warframe/AvatarAbilityStrengthMod",
    name: "Intensify",
    polarity: "madurai",
    rarity: "Rare",
    baseDrain: 6,
    fusionLimit: 5,
    type: "Warframe Mod",
    levelStats: [
      { stats: ["+5% Ability Strength"] },
      { stats: ["+10% Ability Strength"] },
      { stats: ["+15% Ability Strength"] },
      { stats: ["+20% Ability Strength"] },
      { stats: ["+25% Ability Strength"] },
      { stats: ["+30% Ability Strength"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/IntensifyMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Intensify",
    drops: [{ location: "Captain Vor", chance: 0.023 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Warframe/AvatarAbilityDurationMod",
    name: "Continuity",
    polarity: "madurai",
    rarity: "Rare",
    baseDrain: 6,
    fusionLimit: 5,
    type: "Warframe Mod",
    levelStats: [
      { stats: ["+5% Ability Duration"] },
      { stats: ["+10% Ability Duration"] },
      { stats: ["+15% Ability Duration"] },
      { stats: ["+20% Ability Duration"] },
      { stats: ["+25% Ability Duration"] },
      { stats: ["+30% Ability Duration"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/ContinuityMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Continuity",
    drops: [{ location: "General Sargas Ruk", chance: 0.021 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Warframe/AvatarAbilityRangeMod",
    name: "Stretch",
    polarity: "naramon",
    rarity: "Uncommon",
    baseDrain: 4,
    fusionLimit: 5,
    type: "Warframe Mod",
    levelStats: [
      { stats: ["+75% Ability Range"] },
      { stats: ["+15% Ability Range"] },
      { stats: ["+22.5% Ability Range"] },
      { stats: ["+30% Ability Range"] },
      { stats: ["+37.5% Ability Range"] },
      { stats: ["+45% Ability Range"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/StretchMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Stretch",
    drops: [{ location: "Elite Arid Lancer", chance: 0.03 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Warframe/AvatarHealthMod",
    name: "Vitality",
    polarity: "vazarin",
    rarity: "Common",
    baseDrain: 2,
    fusionLimit: 10,
    type: "Warframe Mod",
    levelStats: [
      { stats: ["+40% Health"] },
      { stats: ["+80% Health"] },
      { stats: ["+120% Health"] },
      { stats: ["+160% Health"] },
      { stats: ["+200% Health"] },
      { stats: ["+240% Health"] },
      { stats: ["+280% Health"] },
      { stats: ["+320% Health"] },
      { stats: ["+360% Health"] },
      { stats: ["+400% Health"] },
      { stats: ["+440% Health"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/VitalityMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Vitality",
    drops: [{ location: "Grineer Lancer", chance: 0.1 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Warframe/AvatarShieldMod",
    name: "Redirection",
    polarity: "vazarin",
    rarity: "Common",
    baseDrain: 2,
    fusionLimit: 10,
    type: "Warframe Mod",
    levelStats: [
      { stats: ["+40% Shield Capacity"] },
      { stats: ["+80% Shield Capacity"] },
      { stats: ["+120% Shield Capacity"] },
      { stats: ["+160% Shield Capacity"] },
      { stats: ["+200% Shield Capacity"] },
      { stats: ["+240% Shield Capacity"] },
      { stats: ["+280% Shield Capacity"] },
      { stats: ["+320% Shield Capacity"] },
      { stats: ["+360% Shield Capacity"] },
      { stats: ["+400% Shield Capacity"] },
      { stats: ["+440% Shield Capacity"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/RedirectionMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Redirection",
    drops: [{ location: "Corrupted Crewman", chance: 0.1 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Warframe/AvatarArmorMod",
    name: "Steel Fiber",
    polarity: "vazarin",
    rarity: "Common",
    baseDrain: 2,
    fusionLimit: 10,
    type: "Warframe Mod",
    levelStats: [
      { stats: ["+10% Armor"] },
      { stats: ["+20% Armor"] },
      { stats: ["+30% Armor"] },
      { stats: ["+40% Armor"] },
      { stats: ["+50% Armor"] },
      { stats: ["+60% Armor"] },
      { stats: ["+70% Armor"] },
      { stats: ["+80% Armor"] },
      { stats: ["+90% Armor"] },
      { stats: ["+100% Armor"] },
      { stats: ["+110% Armor"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/SteelFiberMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Steel_Fiber",
    drops: [{ location: "Corrupted Lancer", chance: 0.08 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Warframe/DualStat/TransientFortitude",
    name: "Transient Fortitude",
    polarity: "madurai",
    rarity: "Rare",
    baseDrain: 6,
    fusionLimit: 10,
    type: "Warframe Mod",
    levelStats: [
      { stats: ["+5% Ability Strength", "-2.5% Ability Duration"] },
      { stats: ["+10% Ability Strength", "-5% Ability Duration"] },
      { stats: ["+15% Ability Strength", "-7.5% Ability Duration"] },
      { stats: ["+20% Ability Strength", "-10% Ability Duration"] },
      { stats: ["+25% Ability Strength", "-12.5% Ability Duration"] },
      { stats: ["+30% Ability Strength", "-15% Ability Duration"] },
      { stats: ["+35% Ability Strength", "-17.5% Ability Duration"] },
      { stats: ["+40% Ability Strength", "-20% Ability Duration"] },
      { stats: ["+45% Ability Strength", "-22.5% Ability Duration"] },
      { stats: ["+50% Ability Strength", "-25% Ability Duration"] },
      { stats: ["+55% Ability Strength", "-27.5% Ability Duration"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/TransientFortitudeMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Transient_Fortitude",
    drops: [{ location: "Orokin Vault (Derelict)", chance: 0.0435 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Warframe/DualStat/BlindRage",
    name: "Blind Rage",
    polarity: "madurai",
    rarity: "Rare",
    baseDrain: 6,
    fusionLimit: 10,
    type: "Warframe Mod",
    levelStats: [
      { stats: ["+9% Ability Strength", "-5% Ability Efficiency"] },
      { stats: ["+18% Ability Strength", "-10% Ability Efficiency"] },
      { stats: ["+27% Ability Strength", "-15% Ability Efficiency"] },
      { stats: ["+36% Ability Strength", "-20% Ability Efficiency"] },
      { stats: ["+45% Ability Strength", "-25% Ability Efficiency"] },
      { stats: ["+54% Ability Strength", "-30% Ability Efficiency"] },
      { stats: ["+63% Ability Strength", "-35% Ability Efficiency"] },
      { stats: ["+72% Ability Strength", "-40% Ability Efficiency"] },
      { stats: ["+81% Ability Strength", "-45% Ability Efficiency"] },
      { stats: ["+90% Ability Strength", "-50% Ability Efficiency"] },
      { stats: ["+99% Ability Strength", "-55% Ability Efficiency"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/BlindRageMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Blind_Rage",
    drops: [{ location: "Orokin Vault (Derelict)", chance: 0.0435 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Legendary/PrimedFlow",
    name: "Primed Flow",
    polarity: "naramon",
    rarity: "Legendary",
    baseDrain: 6,
    fusionLimit: 10,
    type: "Warframe Mod",
    levelStats: [
      { stats: ["+25% Energy Max"] },
      { stats: ["+50% Energy Max"] },
      { stats: ["+75% Energy Max"] },
      { stats: ["+100% Energy Max"] },
      { stats: ["+125% Energy Max"] },
      { stats: ["+150% Energy Max"] },
      { stats: ["+175% Energy Max"] },
      { stats: ["+200% Energy Max"] },
      { stats: ["+225% Energy Max"] },
      { stats: ["+250% Energy Max"] },
      { stats: ["+275% Energy Max"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/PrimedFlow.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Primed_Flow",
    drops: [{ location: "Baro Ki'Teer", chance: 1.0 }]
  }
];

export const fallbackArcanes = [
  {
    "id": "akimbo-slip-shot",
    "name": "Akimbo Slip Shot",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionCT.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-acceleration",
    "name": "Arcane Acceleration",
    "category": "Warframe",
    "rarity": "Uncommon",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionAM.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-aegis",
    "name": "Arcane Aegis",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionBA.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-agility",
    "name": "Arcane Agility",
    "category": "Warframe",
    "rarity": "Uncommon",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionAG.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-arachne",
    "name": "Arcane Arachne",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneEnergise.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-avenger",
    "name": "Arcane Avenger",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionAB.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-awakening",
    "name": "Arcane Awakening",
    "category": "Warframe",
    "rarity": "Uncommon",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionAS.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-barrier",
    "name": "Arcane Barrier",
    "category": "Warframe",
    "rarity": "Legendary",
    "description": "",
    "source": "Eidolons (Teralyst/Gantulyst/Hydrolyst)",
    "imageName": "ArcaneProjectionAE.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-battery",
    "name": "Arcane Battery",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionDF.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-bellicose",
    "name": "Arcane Bellicose",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionDI.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-blade-charger",
    "name": "Arcane Blade Charger",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionMeleeDmgOnRifleKill.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-blessing",
    "name": "Arcane Blessing",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionCA.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-bodyguard",
    "name": "Arcane Bodyguard",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionHealCompanionOnSixMeleeKills.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-camisado",
    "name": "Arcane Camisado",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionDP.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-circumvent",
    "name": "Arcane Circumvent",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionDY.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-concentration",
    "name": "Arcane Concentration",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionAO.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-consequence",
    "name": "Arcane Consequence",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons (Teralyst/Gantulyst/Hydrolyst)",
    "imageName": "ArcaneProjectionBH.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-crepuscular",
    "name": "Arcane Crepuscular",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionDQ.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-defense",
    "name": "Arcane Defense",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionPuncture.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-deflection",
    "name": "Arcane Deflection",
    "category": "Warframe",
    "rarity": "Uncommon",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionSlash.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-detoxifier",
    "name": "Arcane Detoxifier",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionPoison.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-double-back",
    "name": "Arcane Double Back",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionCE.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-energize",
    "name": "Arcane Energize",
    "category": "Warframe",
    "rarity": "Legendary",
    "description": "",
    "source": "Eidolons (Teralyst/Gantulyst/Hydrolyst)",
    "imageName": "ArcaneProjectionBI.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-eruption",
    "name": "Arcane Eruption",
    "category": "Warframe",
    "rarity": "Uncommon",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionAU.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-escapist",
    "name": "Arcane Escapist",
    "category": "Warframe",
    "rarity": "Legendary",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionDR.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-expertise",
    "name": "Arcane Expertise",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionEB.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-fury",
    "name": "Arcane Fury",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionBC.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-grace",
    "name": "Arcane Grace",
    "category": "Warframe",
    "rarity": "Legendary",
    "description": "",
    "source": "Eidolons (Teralyst/Gantulyst/Hydrolyst)",
    "imageName": "ArcaneProjectionAC.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-guardian",
    "name": "Arcane Guardian",
    "category": "Warframe",
    "rarity": "Uncommon",
    "description": "",
    "source": "Eidolons (Teralyst/Gantulyst/Hydrolyst)",
    "imageName": "ArcaneProjectionAA.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-healing",
    "name": "Arcane Healing",
    "category": "Warframe",
    "rarity": "Uncommon",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionRadiation.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-hot-shot",
    "name": "Arcane Hot Shot",
    "category": "Warframe",
    "rarity": "Legendary",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionDS.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-ice",
    "name": "Arcane Ice",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionHeat.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-ice-storm",
    "name": "Arcane Ice Storm",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionDD.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-impetus",
    "name": "Arcane Impetus",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionDO.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-intention",
    "name": "Arcane Intention",
    "category": "Warframe",
    "rarity": "Uncommon",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionCJ.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-liquid",
    "name": "Arcane Liquid",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionGas.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-momentum",
    "name": "Arcane Momentum",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionBG.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-nullifier",
    "name": "Arcane Nullifier",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionMagnetic.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-persistence",
    "name": "Arcane Persistence",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionEC.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-phantasm",
    "name": "Arcane Phantasm",
    "category": "Warframe",
    "rarity": "Uncommon",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionAH.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-pistoleer",
    "name": "Arcane Pistoleer",
    "category": "Secondary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionAmmoEfficiencyOnPistolHeadshot.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-power-ramp",
    "name": "Arcane Power Ramp",
    "category": "Secondary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionCR.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-precision",
    "name": "Arcane Precision",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionBD.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-primary-charger",
    "name": "Arcane Primary Charger",
    "category": "Primary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionPrimaryDmgOnMeleeKill.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-protection",
    "name": "Arcane Protection",
    "category": "Warframe",
    "rarity": "Uncommon",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionCorrosive.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-pulse",
    "name": "Arcane Pulse",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionAT.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-rage",
    "name": "Arcane Rage",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionAL.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-reaper",
    "name": "Arcane Reaper",
    "category": "Warframe",
    "rarity": "Legendary",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionCK.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-resistance",
    "name": "Arcane Resistance",
    "category": "Warframe",
    "rarity": "Uncommon",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionPoison.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-rise",
    "name": "Arcane Rise",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionCB.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-shield",
    "name": "Arcane Shield",
    "category": "Warframe",
    "rarity": "Uncommon",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionImpact.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-steadfast",
    "name": "Arcane Steadfast",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionCF.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-strike",
    "name": "Arcane Strike",
    "category": "Warframe",
    "rarity": "Uncommon",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionAN.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-survival",
    "name": "Arcane Survival",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionAV.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-tanker",
    "name": "Arcane Tanker",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionArmorOnHeavyGunEquipped.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-temperance",
    "name": "Arcane Temperance",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionAR.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-tempo",
    "name": "Arcane Tempo",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionBF.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-trickery",
    "name": "Arcane Trickery",
    "category": "Warframe",
    "rarity": "Uncommon",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionAQ.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-truculence",
    "name": "Arcane Truculence",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionDN.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-ultimatum",
    "name": "Arcane Ultimatum",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionBB.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-universal-fallout",
    "name": "Arcane Universal Fallout",
    "category": "Warframe",
    "rarity": "Legendary",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionDT.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-velocity",
    "name": "Arcane Velocity",
    "category": "Warframe",
    "rarity": "Uncommon",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionBE.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-victory",
    "name": "Arcane Victory",
    "category": "Warframe",
    "rarity": "Uncommon",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionAJ.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "arcane-warmth",
    "name": "Arcane Warmth",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionCold.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "cascadia-accuracy",
    "name": "Cascadia Accuracy",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Zariman (Cavalero)",
    "imageName": "ArcaneProjectionBU.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "cascadia-empowered",
    "name": "Cascadia Empowered",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Zariman (Cavalero)",
    "imageName": "ArcaneProjectionBT.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "cascadia-flare",
    "name": "Cascadia Flare",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Zariman (Cavalero)",
    "imageName": "ArcaneProjectionBY.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "cascadia-overcharge",
    "name": "Cascadia Overcharge",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Zariman (Cavalero)",
    "imageName": "ArcaneProjectionBL.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "conjunction-voltage",
    "name": "Conjunction Voltage",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionCD.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "emergence-dissipate",
    "name": "Emergence Dissipate",
    "category": "Operator",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionBR.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "emergence-renewed",
    "name": "Emergence Renewed",
    "category": "Operator",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionBQ.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "emergence-savior",
    "name": "Emergence Savior",
    "category": "Operator",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionBS.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "eternal-eradicate",
    "name": "Eternal Eradicate",
    "category": "Operator",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionBP.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "eternal-logistics",
    "name": "Eternal Logistics",
    "category": "Operator",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionBW.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "eternal-onslaught",
    "name": "Eternal Onslaught",
    "category": "Operator",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionBV.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "exodia-brave",
    "name": "Exodia Brave",
    "category": "Secondary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "MeleeArcaneA.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "exodia-contagion",
    "name": "Exodia Contagion",
    "category": "Secondary",
    "rarity": "Legendary",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "MeleeArcaneProjectileOnJump.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "exodia-epidemic",
    "name": "Exodia Epidemic",
    "category": "Secondary",
    "rarity": "Legendary",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "MeleeArcaneShockwaveOnJump.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "exodia-force",
    "name": "Exodia Force",
    "category": "Secondary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "MeleeArcaneF.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "exodia-hunt",
    "name": "Exodia Hunt",
    "category": "Secondary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "MeleeArcaneE.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "exodia-might",
    "name": "Exodia Might",
    "category": "Secondary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "MeleeArcaneC.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "exodia-triumph",
    "name": "Exodia Triumph",
    "category": "Secondary",
    "rarity": "Uncommon",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "MeleeArcaneD.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "exodia-valor",
    "name": "Exodia Valor",
    "category": "Secondary",
    "rarity": "Uncommon",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "MeleeArcaneB.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "fractalized-reset",
    "name": "Fractalized Reset",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionBO.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "longbow-sharpshot",
    "name": "Longbow Sharpshot",
    "category": "Warframe",
    "rarity": "Legendary",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionCL.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "magus-accelerant",
    "name": "Magus Accelerant",
    "category": "Operator",
    "rarity": "Rare",
    "description": "",
    "source": "Quills (Cetus) / Vox Solaris (Fortuna)",
    "imageName": "SolarisMagusAccelerant.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "magus-aggress",
    "name": "Magus Aggress",
    "category": "Operator",
    "rarity": "Uncommon",
    "description": "",
    "source": "Quills (Cetus) / Vox Solaris (Fortuna)",
    "imageName": "ArcaneProjectionCQ.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "magus-anomaly",
    "name": "Magus Anomaly",
    "category": "Operator",
    "rarity": "Rare",
    "description": "",
    "source": "Quills (Cetus) / Vox Solaris (Fortuna)",
    "imageName": "SolarisMagusAnomaly.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "magus-cadence",
    "name": "Magus Cadence",
    "category": "Operator",
    "rarity": "Uncommon",
    "description": "",
    "source": "Quills (Cetus) / Vox Solaris (Fortuna)",
    "imageName": "SpeedOnVoidDash.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "magus-cloud",
    "name": "Magus Cloud",
    "category": "Operator",
    "rarity": "Uncommon",
    "description": "",
    "source": "Quills (Cetus) / Vox Solaris (Fortuna)",
    "imageName": "ImmunityFallDamageOnVoidDamage.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "magus-destruct",
    "name": "Magus Destruct",
    "category": "Operator",
    "rarity": "Rare",
    "description": "",
    "source": "Quills (Cetus) / Vox Solaris (Fortuna)",
    "imageName": "SolarisMagusDestruct.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "magus-drive",
    "name": "Magus Drive",
    "category": "Operator",
    "rarity": "Rare",
    "description": "",
    "source": "Quills (Cetus) / Vox Solaris (Fortuna)",
    "imageName": "SolarisMagusDrive.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "magus-elevate",
    "name": "Magus Elevate",
    "category": "Operator",
    "rarity": "Rare",
    "description": "",
    "source": "Quills (Cetus) / Vox Solaris (Fortuna)",
    "imageName": "HealOnTransferenceIn.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "magus-firewall",
    "name": "Magus Firewall",
    "category": "Operator",
    "rarity": "Rare",
    "description": "",
    "source": "Quills (Cetus) / Vox Solaris (Fortuna)",
    "imageName": "SolarisMagusFirewall.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "magus-glitch",
    "name": "Magus Glitch",
    "category": "Operator",
    "rarity": "Uncommon",
    "description": "",
    "source": "Quills (Cetus) / Vox Solaris (Fortuna)",
    "imageName": "SolarisMagusGlitch.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "magus-husk",
    "name": "Magus Husk",
    "category": "Operator",
    "rarity": "Rare",
    "description": "",
    "source": "Quills (Cetus) / Vox Solaris (Fortuna)",
    "imageName": "ArmourOnOperatorMode.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "magus-lockdown",
    "name": "Magus Lockdown",
    "category": "Operator",
    "rarity": "Rare",
    "description": "",
    "source": "Quills (Cetus) / Vox Solaris (Fortuna)",
    "imageName": "SolarisMagusLockdown.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "magus-melt",
    "name": "Magus Melt",
    "category": "Operator",
    "rarity": "Rare",
    "description": "",
    "source": "Quills (Cetus) / Vox Solaris (Fortuna)",
    "imageName": "SolarisMagusMelt.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "magus-nourish",
    "name": "Magus Nourish",
    "category": "Operator",
    "rarity": "Rare",
    "description": "",
    "source": "Quills (Cetus) / Vox Solaris (Fortuna)",
    "imageName": "HealOnTransferenceOut.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "magus-overload",
    "name": "Magus Overload",
    "category": "Operator",
    "rarity": "Rare",
    "description": "",
    "source": "Quills (Cetus) / Vox Solaris (Fortuna)",
    "imageName": "SolarisMagusOverload.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "magus-repair",
    "name": "Magus Repair",
    "category": "Operator",
    "rarity": "Uncommon",
    "description": "",
    "source": "Quills (Cetus) / Vox Solaris (Fortuna)",
    "imageName": "SolarisMagusRepair.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "magus-replenish",
    "name": "Magus Replenish",
    "category": "Operator",
    "rarity": "Uncommon",
    "description": "",
    "source": "Quills (Cetus) / Vox Solaris (Fortuna)",
    "imageName": "HealOnVoidDash.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "magus-revert",
    "name": "Magus Revert",
    "category": "Operator",
    "rarity": "Rare",
    "description": "",
    "source": "Quills (Cetus) / Vox Solaris (Fortuna)",
    "imageName": "SolarisMagusRevert.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "magus-vigor",
    "name": "Magus Vigor",
    "category": "Operator",
    "rarity": "Rare",
    "description": "",
    "source": "Quills (Cetus) / Vox Solaris (Fortuna)",
    "imageName": "HealthOnOperatorMode.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "melee-afflictions",
    "name": "Melee Afflictions",
    "category": "Secondary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionDH.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "melee-animosity",
    "name": "Melee Animosity",
    "category": "Secondary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionCV.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "melee-careen",
    "name": "Melee Careen",
    "category": "Secondary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionDX.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "melee-crescendo",
    "name": "Melee Crescendo",
    "category": "Secondary",
    "rarity": "Legendary",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionDB.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "melee-doughty",
    "name": "Melee Doughty",
    "category": "Secondary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionDM.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "melee-duplicate",
    "name": "Melee Duplicate",
    "category": "Secondary",
    "rarity": "Legendary",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionCW.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "melee-exposure",
    "name": "Melee Exposure",
    "category": "Secondary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionCY.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "melee-fortification",
    "name": "Melee Fortification",
    "category": "Secondary",
    "rarity": "Uncommon",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionDA.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "melee-influence",
    "name": "Melee Influence",
    "category": "Secondary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionCZ.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "melee-retaliation",
    "name": "Melee Retaliation",
    "category": "Secondary",
    "rarity": "Uncommon",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionCX.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "melee-vortex",
    "name": "Melee Vortex",
    "category": "Secondary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionDC.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "molt-augmented",
    "name": "Molt Augmented",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Zariman (Cavalero)",
    "imageName": "ArcaneProjectionBX.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "molt-efficiency",
    "name": "Molt Efficiency",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Zariman (Cavalero)",
    "imageName": "ArcaneProjectionBN.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "molt-reconstruct",
    "name": "Molt Reconstruct",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Zariman (Cavalero)",
    "imageName": "ArcaneProjectionBZ.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "molt-vigor",
    "name": "Molt Vigor",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Zariman (Cavalero)",
    "imageName": "ArcaneProjectionBM.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "pax-bolt",
    "name": "Pax Bolt",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "SolarisEnergyEfficiency.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "pax-charge",
    "name": "Pax Charge",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "SolarisBulletToBattery.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "pax-seeker",
    "name": "Pax Seeker",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "SolarisSeekerProjOnHeadshotKill.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "pax-soar",
    "name": "Pax Soar",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "SolarisEyeInTheSky.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "primary-blight",
    "name": "Primary Blight",
    "category": "Primary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionCS.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "primary-bulwark",
    "name": "Primary Bulwark",
    "category": "Primary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionDU.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "primary-crux",
    "name": "Primary Crux",
    "category": "Primary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionDK.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "primary-deadhead",
    "name": "Primary Deadhead",
    "category": "Primary",
    "rarity": "Rare",
    "description": "",
    "source": "Steel Path Acolytes",
    "imageName": "ArcaneProjectionSteelPathPrecisionHeadshotB.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "primary-debilitate",
    "name": "Primary Debilitate",
    "category": "Primary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionDW.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "primary-dexterity",
    "name": "Primary Dexterity",
    "category": "Primary",
    "rarity": "Rare",
    "description": "",
    "source": "Steel Path Acolytes",
    "imageName": "ArcaneProjectionSteelPathMeleeToolsB.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "primary-exhilarate",
    "name": "Primary Exhilarate",
    "category": "Primary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionCN.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "primary-frostbite",
    "name": "Primary Frostbite",
    "category": "Primary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionCC.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "primary-merciless",
    "name": "Primary Merciless",
    "category": "Primary",
    "rarity": "Rare",
    "description": "",
    "source": "Steel Path Acolytes",
    "imageName": "ArcaneProjectionSteelPathWarcrimesB.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "primary-obstruct",
    "name": "Primary Obstruct",
    "category": "Primary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionCM.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "primary-overcharge",
    "name": "Primary Overcharge",
    "category": "Primary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionEA.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "primary-plated-round",
    "name": "Primary Plated Round",
    "category": "Primary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionCH.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "residual-boils",
    "name": "Residual Boils",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ResidualLesions.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "residual-malodor",
    "name": "Residual Malodor",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ResidualMiasma.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "residual-shock",
    "name": "Residual Shock",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ResidualShock.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "residual-viremia",
    "name": "Residual Viremia",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ResidualViremia.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "secondary-deadhead",
    "name": "Secondary Deadhead",
    "category": "Secondary",
    "rarity": "Rare",
    "description": "",
    "source": "Steel Path Acolytes",
    "imageName": "ArcaneProjectionSteelPathPrecisionHeadshotA.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "secondary-dexterity",
    "name": "Secondary Dexterity",
    "category": "Secondary",
    "rarity": "Rare",
    "description": "",
    "source": "Steel Path Acolytes",
    "imageName": "ArcaneProjectionSteelPathMeleeToolsA.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "secondary-encumber",
    "name": "Secondary Encumber",
    "category": "Secondary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionCG.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "secondary-enervate",
    "name": "Secondary Enervate",
    "category": "Secondary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionDL.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "secondary-fortifier",
    "name": "Secondary Fortifier",
    "category": "Secondary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionDG.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "secondary-irradiate",
    "name": "Secondary Irradiate",
    "category": "Secondary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionDV.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "secondary-kinship",
    "name": "Secondary Kinship",
    "category": "Secondary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionCI.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "secondary-merciless",
    "name": "Secondary Merciless",
    "category": "Secondary",
    "rarity": "Rare",
    "description": "",
    "source": "Steel Path Acolytes",
    "imageName": "ArcaneProjectionSteelPathWarcrimesA.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "secondary-outburst",
    "name": "Secondary Outburst",
    "category": "Secondary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionCU.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "secondary-shiver",
    "name": "Secondary Shiver",
    "category": "Secondary",
    "rarity": "Legendary",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionCP.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "secondary-surge",
    "name": "Secondary Surge",
    "category": "Secondary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionDE.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "shotgun-vendetta",
    "name": "Shotgun Vendetta",
    "category": "Primary",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "ArcaneProjectionCO.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "theorem-contagion",
    "name": "Theorem Contagion",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "TheoremContagion.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "theorem-demulcent",
    "name": "Theorem Demulcent",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "TheoremDemulcent.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "theorem-infection",
    "name": "Theorem Infection",
    "category": "Warframe",
    "rarity": "Rare",
    "description": "",
    "source": "Eidolons / Steel Path / Cavalero",
    "imageName": "TheoremInfection.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "virtuos-forge",
    "name": "Virtuos Forge",
    "category": "Secondary",
    "rarity": "Uncommon",
    "description": "",
    "source": "Quills (Cetus) / Vox Solaris (Fortuna)",
    "imageName": "SolarisVirtuosForge.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "virtuos-fury",
    "name": "Virtuos Fury",
    "category": "Secondary",
    "rarity": "Uncommon",
    "description": "",
    "source": "Quills (Cetus) / Vox Solaris (Fortuna)",
    "imageName": "IncreasedDamageOnStatusProc.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "virtuos-ghost",
    "name": "Virtuos Ghost",
    "category": "Secondary",
    "rarity": "Rare",
    "description": "",
    "source": "Quills (Cetus) / Vox Solaris (Fortuna)",
    "imageName": "StatusChanceOnHeadshot.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "virtuos-null",
    "name": "Virtuos Null",
    "category": "Secondary",
    "rarity": "Rare",
    "description": "",
    "source": "Quills (Cetus) / Vox Solaris (Fortuna)",
    "imageName": "OperatorAmmoRegenOnKill.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "virtuos-shadow",
    "name": "Virtuos Shadow",
    "category": "Secondary",
    "rarity": "Rare",
    "description": "",
    "source": "Quills (Cetus) / Vox Solaris (Fortuna)",
    "imageName": "CriticalChanceOnHeadshot.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "virtuos-spike",
    "name": "Virtuos Spike",
    "category": "Secondary",
    "rarity": "Rare",
    "description": "",
    "source": "Quills (Cetus) / Vox Solaris (Fortuna)",
    "imageName": "SolarisVirtuosSpike.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "virtuos-strike",
    "name": "Virtuos Strike",
    "category": "Secondary",
    "rarity": "Uncommon",
    "description": "",
    "source": "Quills (Cetus) / Vox Solaris (Fortuna)",
    "imageName": "IncreasedCriticalDamageOnCriticalStrike.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "virtuos-surge",
    "name": "Virtuos Surge",
    "category": "Secondary",
    "rarity": "Rare",
    "description": "",
    "source": "Quills (Cetus) / Vox Solaris (Fortuna)",
    "imageName": "SolarisVirtuosSurge.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "virtuos-tempo",
    "name": "Virtuos Tempo",
    "category": "Secondary",
    "rarity": "Rare",
    "description": "",
    "source": "Quills (Cetus) / Vox Solaris (Fortuna)",
    "imageName": "AttackSpeedOnKill.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  },
  {
    "id": "virtuos-trojan",
    "name": "Virtuos Trojan",
    "category": "Secondary",
    "rarity": "Uncommon",
    "description": "",
    "source": "Quills (Cetus) / Vox Solaris (Fortuna)",
    "imageName": "SolarisVirtuosTrojan.png",
    "wikiaUrl": "",
    "wikiaThumbnail": ""
  }
];
