// Fallback database of popular/essential Warframe mods.
// Used when the external API is loading or unreachable.

export const fallbackMods = [
  {
    uniqueName: "/Lotus/Upgrades/Mods/Rifle/RifleDamageMod",
    name: "Serration",
    polarity: "madurai",
    rarity: "Uncommon",
    baseDrain: 4,
    fusionLimit: 10,
    type: "Rifle Mod",
    levelStats: [
      { stats: ["+15% Damage"] },
      { stats: ["+30% Damage"] },
      { stats: ["+45% Damage"] },
      { stats: ["+60% Damage"] },
      { stats: ["+75% Damage"] },
      { stats: ["+90% Damage"] },
      { stats: ["+105% Damage"] },
      { stats: ["+120% Damage"] },
      { stats: ["+135% Damage"] },
      { stats: ["+150% Damage"] },
      { stats: ["+165% Damage"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/SerrationMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Serration",
    drops: [{ location: "Grineer Elite Lancer", chance: 0.02 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Rifle/RifleMultishotMod",
    name: "Split Chamber",
    polarity: "madurai",
    rarity: "Rare",
    baseDrain: 10,
    fusionLimit: 5,
    type: "Rifle Mod",
    levelStats: [
      { stats: ["+15% Multishot"] },
      { stats: ["+30% Multishot"] },
      { stats: ["+45% Multishot"] },
      { stats: ["+60% Multishot"] },
      { stats: ["+75% Multishot"] },
      { stats: ["+90% Multishot"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/SplitChamberMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Split_Chamber",
    drops: [{ location: "Tier 3 Defense Rewards", chance: 0.0251 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Pistol/PistolDamageMod",
    name: "Hornet Strike",
    polarity: "madurai",
    rarity: "Uncommon",
    baseDrain: 4,
    fusionLimit: 10,
    type: "Secondary Mod",
    levelStats: [
      { stats: ["+20% Damage"] },
      { stats: ["+40% Damage"] },
      { stats: ["+60% Damage"] },
      { stats: ["+80% Damage"] },
      { stats: ["+100% Damage"] },
      { stats: ["+120% Damage"] },
      { stats: ["+140% Damage"] },
      { stats: ["+160% Damage"] },
      { stats: ["+180% Damage"] },
      { stats: ["+200% Damage"] },
      { stats: ["+220% Damage"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/HornetStrikeMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Hornet_Strike",
    drops: [{ location: "Grineer Heavy Gunner", chance: 0.05 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Pistol/PistolMultishotMod",
    name: "Barrel Diffusion",
    polarity: "madurai",
    rarity: "Rare",
    baseDrain: 6,
    fusionLimit: 5,
    type: "Secondary Mod",
    levelStats: [
      { stats: ["+20% Multishot"] },
      { stats: ["+40% Multishot"] },
      { stats: ["+60% Multishot"] },
      { stats: ["+80% Multishot"] },
      { stats: ["+100% Multishot"] },
      { stats: ["+120% Multishot"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/BarrelDiffusionMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Barrel_Diffusion",
    drops: [{ location: "Seeker", chance: 0.03 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Melee/MeleeDamageMod",
    name: "Pressure Point",
    polarity: "madurai",
    rarity: "Common",
    baseDrain: 4,
    fusionLimit: 5,
    type: "Melee Mod",
    levelStats: [
      { stats: ["+20% Melee Damage"] },
      { stats: ["+40% Melee Damage"] },
      { stats: ["+60% Melee Damage"] },
      { stats: ["+80% Melee Damage"] },
      { stats: ["+100% Melee Damage"] },
      { stats: ["+120% Melee Damage"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/PressurePointMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Pressure_Point",
    drops: [{ location: "Corrupted Lancer", chance: 0.1 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Warframe/AvatarPowerMaxMod",
    name: "Flow",
    polarity: "naramon",
    rarity: "Rare",
    baseDrain: 4,
    fusionLimit: 5,
    type: "Warframe Mod",
    levelStats: [
      { stats: ["+25% Energy Max"] },
      { stats: ["+50% Energy Max"] },
      { stats: ["+75% Energy Max"] },
      { stats: ["+100% Energy Max"] },
      { stats: ["+125% Energy Max"] },
      { stats: ["+150% Energy Max"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/FlowMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Flow",
    drops: [{ location: "Butcher", chance: 0.02 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Warframe/AvatarPowerEfficiencyMod",
    name: "Streamline",
    polarity: "naramon",
    rarity: "Rare",
    baseDrain: 4,
    fusionLimit: 5,
    type: "Warframe Mod",
    levelStats: [
      { stats: ["+5% Ability Efficiency"] },
      { stats: ["+10% Ability Efficiency"] },
      { stats: ["+15% Ability Efficiency"] },
      { stats: ["+20% Ability Efficiency"] },
      { stats: ["+25% Ability Efficiency"] },
      { stats: ["+30% Ability Efficiency"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/StreamlineMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Streamline",
    drops: [{ location: "Corrupted Crewman", chance: 0.02 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Warframe/AvatarAbilityStrengthMod",
    name: "Intensify",
    polarity: "madurai",
    rarity: "Rare",
    baseDrain: 6,
    fusionLimit: 5,
    type: "Warframe Mod",
    levelStats: [
      { stats: ["+5% Ability Strength"] },
      { stats: ["+10% Ability Strength"] },
      { stats: ["+15% Ability Strength"] },
      { stats: ["+20% Ability Strength"] },
      { stats: ["+25% Ability Strength"] },
      { stats: ["+30% Ability Strength"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/IntensifyMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Intensify",
    drops: [{ location: "Captain Vor", chance: 0.023 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Warframe/AvatarAbilityDurationMod",
    name: "Continuity",
    polarity: "madurai",
    rarity: "Rare",
    baseDrain: 6,
    fusionLimit: 5,
    type: "Warframe Mod",
    levelStats: [
      { stats: ["+5% Ability Duration"] },
      { stats: ["+10% Ability Duration"] },
      { stats: ["+15% Ability Duration"] },
      { stats: ["+20% Ability Duration"] },
      { stats: ["+25% Ability Duration"] },
      { stats: ["+30% Ability Duration"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/ContinuityMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Continuity",
    drops: [{ location: "General Sargas Ruk", chance: 0.021 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Warframe/AvatarAbilityRangeMod",
    name: "Stretch",
    polarity: "naramon",
    rarity: "Uncommon",
    baseDrain: 4,
    fusionLimit: 5,
    type: "Warframe Mod",
    levelStats: [
      { stats: ["+75% Ability Range"] },
      { stats: ["+15% Ability Range"] },
      { stats: ["+22.5% Ability Range"] },
      { stats: ["+30% Ability Range"] },
      { stats: ["+37.5% Ability Range"] },
      { stats: ["+45% Ability Range"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/StretchMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Stretch",
    drops: [{ location: "Elite Arid Lancer", chance: 0.03 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Warframe/AvatarHealthMod",
    name: "Vitality",
    polarity: "vazarin",
    rarity: "Common",
    baseDrain: 2,
    fusionLimit: 10,
    type: "Warframe Mod",
    levelStats: [
      { stats: ["+40% Health"] },
      { stats: ["+80% Health"] },
      { stats: ["+120% Health"] },
      { stats: ["+160% Health"] },
      { stats: ["+200% Health"] },
      { stats: ["+240% Health"] },
      { stats: ["+280% Health"] },
      { stats: ["+320% Health"] },
      { stats: ["+360% Health"] },
      { stats: ["+400% Health"] },
      { stats: ["+440% Health"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/VitalityMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Vitality",
    drops: [{ location: "Grineer Lancer", chance: 0.1 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Warframe/AvatarShieldMod",
    name: "Redirection",
    polarity: "vazarin",
    rarity: "Common",
    baseDrain: 2,
    fusionLimit: 10,
    type: "Warframe Mod",
    levelStats: [
      { stats: ["+40% Shield Capacity"] },
      { stats: ["+80% Shield Capacity"] },
      { stats: ["+120% Shield Capacity"] },
      { stats: ["+160% Shield Capacity"] },
      { stats: ["+200% Shield Capacity"] },
      { stats: ["+240% Shield Capacity"] },
      { stats: ["+280% Shield Capacity"] },
      { stats: ["+320% Shield Capacity"] },
      { stats: ["+360% Shield Capacity"] },
      { stats: ["+400% Shield Capacity"] },
      { stats: ["+440% Shield Capacity"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/RedirectionMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Redirection",
    drops: [{ location: "Corrupted Crewman", chance: 0.1 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Warframe/AvatarArmorMod",
    name: "Steel Fiber",
    polarity: "vazarin",
    rarity: "Common",
    baseDrain: 2,
    fusionLimit: 10,
    type: "Warframe Mod",
    levelStats: [
      { stats: ["+10% Armor"] },
      { stats: ["+20% Armor"] },
      { stats: ["+30% Armor"] },
      { stats: ["+40% Armor"] },
      { stats: ["+50% Armor"] },
      { stats: ["+60% Armor"] },
      { stats: ["+70% Armor"] },
      { stats: ["+80% Armor"] },
      { stats: ["+90% Armor"] },
      { stats: ["+100% Armor"] },
      { stats: ["+110% Armor"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/SteelFiberMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Steel_Fiber",
    drops: [{ location: "Corrupted Lancer", chance: 0.08 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Warframe/DualStat/TransientFortitude",
    name: "Transient Fortitude",
    polarity: "madurai",
    rarity: "Rare",
    baseDrain: 6,
    fusionLimit: 10,
    type: "Warframe Mod",
    levelStats: [
      { stats: ["+5% Ability Strength", "-2.5% Ability Duration"] },
      { stats: ["+10% Ability Strength", "-5% Ability Duration"] },
      { stats: ["+15% Ability Strength", "-7.5% Ability Duration"] },
      { stats: ["+20% Ability Strength", "-10% Ability Duration"] },
      { stats: ["+25% Ability Strength", "-12.5% Ability Duration"] },
      { stats: ["+30% Ability Strength", "-15% Ability Duration"] },
      { stats: ["+35% Ability Strength", "-17.5% Ability Duration"] },
      { stats: ["+40% Ability Strength", "-20% Ability Duration"] },
      { stats: ["+45% Ability Strength", "-22.5% Ability Duration"] },
      { stats: ["+50% Ability Strength", "-25% Ability Duration"] },
      { stats: ["+55% Ability Strength", "-27.5% Ability Duration"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/TransientFortitudeMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Transient_Fortitude",
    drops: [{ location: "Orokin Vault (Derelict)", chance: 0.0435 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Warframe/DualStat/BlindRage",
    name: "Blind Rage",
    polarity: "madurai",
    rarity: "Rare",
    baseDrain: 6,
    fusionLimit: 10,
    type: "Warframe Mod",
    levelStats: [
      { stats: ["+9% Ability Strength", "-5% Ability Efficiency"] },
      { stats: ["+18% Ability Strength", "-10% Ability Efficiency"] },
      { stats: ["+27% Ability Strength", "-15% Ability Efficiency"] },
      { stats: ["+36% Ability Strength", "-20% Ability Efficiency"] },
      { stats: ["+45% Ability Strength", "-25% Ability Efficiency"] },
      { stats: ["+54% Ability Strength", "-30% Ability Efficiency"] },
      { stats: ["+63% Ability Strength", "-35% Ability Efficiency"] },
      { stats: ["+72% Ability Strength", "-40% Ability Efficiency"] },
      { stats: ["+81% Ability Strength", "-45% Ability Efficiency"] },
      { stats: ["+90% Ability Strength", "-50% Ability Efficiency"] },
      { stats: ["+99% Ability Strength", "-55% Ability Efficiency"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/BlindRageMod.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Blind_Rage",
    drops: [{ location: "Orokin Vault (Derelict)", chance: 0.0435 }]
  },
  {
    uniqueName: "/Lotus/Upgrades/Mods/Legendary/PrimedFlow",
    name: "Primed Flow",
    polarity: "naramon",
    rarity: "Legendary",
    baseDrain: 6,
    fusionLimit: 10,
    type: "Warframe Mod",
    levelStats: [
      { stats: ["+25% Energy Max"] },
      { stats: ["+50% Energy Max"] },
      { stats: ["+75% Energy Max"] },
      { stats: ["+100% Energy Max"] },
      { stats: ["+125% Energy Max"] },
      { stats: ["+150% Energy Max"] },
      { stats: ["+175% Energy Max"] },
      { stats: ["+200% Energy Max"] },
      { stats: ["+225% Energy Max"] },
      { stats: ["+250% Energy Max"] },
      { stats: ["+275% Energy Max"] }
    ],
    wikiaThumbnail: "https://wiki.warframe.com/images/PrimedFlow.png",
    wikiaUrl: "https://warframe.fandom.com/wiki/Primed_Flow",
    drops: [{ location: "Baro Ki'Teer", chance: 1.0 }]
  }
];
