export const weaponSourceMap = {
  "/Lotus/Weapons/Grineer/Melee/GrineerTylAxeAndBoar/RegorAxeShield": "Dojo Chem Lab",
  "/Lotus/Weapons/ClanTech/Bio/AcidDartPistol": "Dojo Bio Lab",
  "/Lotus/Weapons/Tenno/Akimbo/AkimboAutoPistols": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Archwing/Melee/ArchSwordHook/ArchHookSwordWeapon": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Akimbo/AkimboBolto": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Akimbo/AkimboShotGun": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Pistols/TigrisRedeemerSetPistol/TnoBladedPistols": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/Akimbo/AkLexPistols": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Akimbo/DualMagnus": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/Pistols/SomaSidearm/AkimboSomaPistols": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/Pistols/TennoUzi/TennoUzi": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Akimbo/DualVastos": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/Pistols/HarlequinGun/HarlequinPistols": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Melee/Staff/GrnStaff": "Market Blueprint",
  "/Lotus/Weapons/Corpus/LongGuns/ChainLightningGun/ChainLightningRifle": "Dojo Energy Lab",
  "/Lotus/Weapons/Corpus/Pistols/CrpHandRL/CorpusHandRocketLauncher": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Melee/Scythe/ParisScythe/ParisScythe": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/Melee/Gauntlet/Gauntlet": "Market Blueprint",
  "/Lotus/Weapons/Corpus/LongGuns/CrpShotgun/CrpShotgun": "Dojo Energy Lab",
  "/Lotus/Weapons/Corpus/Pistols/SniperPistol/CrpScopeGun": "Dojo Energy Lab",
  "/Lotus/Weapons/Corpus/Melee/Hammer/CorpusHammerWeapon": "Market Blueprint",
  "/Lotus/Weapons/Grineer/LongGuns/LaserAimRifle/LaserAimRifle": "Dojo Chem Lab",
  "/Lotus/Weapons/Tenno/LongGuns/TnGlassShotgun/TnGlassShotgunGun": "Market Blueprint",
  "/Lotus/Weapons/Grineer/Pistols/HeatGun/GrnHeatGun": "Market Blueprint",
  "/Lotus/Weapons/Grineer/Melee/GrineerWhip/GrineerWhip": "Market Blueprint",
  "/Lotus/Weapons/Tenno/LongGuns/TnoPrmryXbow/TnoPrmryXbowWeapon": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/Pistols/SundialGun/SundialPistol": "Daily Login",
  "/Lotus/Weapons/Tenno/Melee/Swords/DaxDuviriTwoHandedKatana/DaxDuviriTwoHandedKatanaWeapon": "Duviri Acrithis",
  "/Lotus/Weapons/Tenno/Pistols/AutomaticHandCrossbow/AutoCrossBow": "Market Blueprint",
  "/Lotus/Weapons/Corpus/LongGuns/CrpSentExperimentRifle/CrpSentExperimentRifle": "Market Blueprint",
  "/Lotus/Weapons/Tenno/LongGuns/TnSMG/TnSMGWeapon": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/Melee/Staff/Staff": "Market Credits",
  "/Lotus/Weapons/Tenno/Melee/Tonfa/Boltonfa/Boltonfa": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/Pistol/CrossBow": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Rifle/BoltoRifle": "Market Blueprint",
  "/Lotus/Weapons/Grineer/Pistols/GrineerHandShotgun/GrineerHandCannon": "Grustrag Three",
  "/Lotus/Weapons/Tenno/Rifle/Rifle": "Market Credits",
  "/Lotus/Weapons/Tenno/Melee/Swords/StalkerTwo/StalkerTwoSmallSword": "Quest (Broken War)",
  "/Lotus/Weapons/Tenno/Pistol/HandShotGun": "Market Blueprint",
  "/Lotus/Weapons/Infested/LongGuns/InfArmCannon/InfArmCannon": "Dojo Bio Lab",
  "/Lotus/Weapons/Tenno/Rifle/BurstRifle": "Market Blueprint",
  "/Lotus/Weapons/Grineer/LongGuns/GrnGorgSniperRifle/GrnGorgSniperRifle": "Dojo Chem Lab",
  "/Lotus/Weapons/Tenno/Melee/Staff/SingleStaff": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Melee/Polearms/TnHalberdPolearm/TnHalberdPolearmWeapon": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/ThrowingWeapons/StickyBomb/StickyBombs": "Dojo Tenno Lab",
  "/Lotus/Weapons/Infested/Pistols/InfBeamPistol/InfBeamPistol": "Dojo Bio Lab",
  "/Lotus/Weapons/Infested/Melee/InfEmbolistScythe/InfestedScythe": "Dojo Bio Lab",
  "/Lotus/Weapons/Tenno/Archwing/Melee/Archswordandshield/ArchSwordShield": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Melee/Dagger/CeramicDagger": "Nightwave",
  "/Lotus/Weapons/Infested/Melee/Glaives/PunctureGlaive/PunctureGlaiveWeapon": "Dojo Bio Lab",
  "/Lotus/Weapons/Tenno/Bows/AntlerBow/AntlerBow": "Market Blueprint",
  "/Lotus/Weapons/Corpus/Pistols/CorpusMinigun/CorpusMinigun": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Melee/SwordsAndBoards/PacifistShieldAndSword/PacifistShieldSword": "Market Blueprint",
  "/Lotus/Weapons/Corpus/LongGuns/CrpSplitLaser/CrpSplitLaser": "Dojo Energy Lab",
  "/Lotus/Weapons/Tenno/LongGuns/TnHeavyShotgun/TnHeavyShotgunGun": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Archwing/Primary/LaunchGrenade/ArchCannon": "Market Blueprint",
  "/Lotus/Weapons/Corpus/Pistols/CrpSentAmalgPistol/CrpSentAmalgPistol": "Dojo Energy Lab",
  "/Lotus/Weapons/Corpus/Pistols/CrpChargeGun/CrpChargeGun": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Archwing/Primary/ArchBurstGun/ArchBurstGun": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Bows/AsymetricalBow/AsymetricalBow": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/Melee/Dagger/DarkDagger": "Nightwave",
  "/Lotus/Weapons/Tenno/Melee/Swords/DarkSword/DarkSwordDaggerHybridWeapon": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/Melee/Swords/DarkSword/DarkLongSword": "Nightwave",
  "/Lotus/Weapons/ClanTech/Energy/EnergyRifle": "Dojo Energy Lab",
  "/Lotus/Weapons/ClanTech/Energy/DeraVandal": "Dojo Energy Lab",
  "/Lotus/Weapons/Tenno/Melee/Swords/TnoRapier/TnoRapier": "Dojo Tenno Lab",
  "/Lotus/Weapons/Corpus/Pistols/CorpusHandShotgun/CorpusHandCannon": "Zanuka Hunter",
  "/Lotus/Weapons/Tenno/Melee/Swords/DexTheSecond/DexTheSecond": "Quest",
  "/Lotus/Weapons/Tenno/Melee/Swords/TnDagathBladeWhip/TnDagathBladeWhip": "Dojo Dagath Hollow",
  "/Lotus/Weapons/Tenno/Melee/Swords/KatanaAndWakizashi/LowKatana": "Market Blueprint",
  "/Lotus/Weapons/Grineer/LongGuns/GrineerFlakCannon/FlakCannon": "Market Blueprint",
  "/Lotus/Weapons/Corpus/Pistols/CorpusMinigun/DualCorpusMinigun": "Dojo Energy Lab",
  "/Lotus/Weapons/Grineer/Melee/GrineerMachetteAndCleaver/DualCleaverWeapon": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Archwing/Primary/ArchwingHeavyPistols/ArchHeavyPistols": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Melee/DualShortSword/DualEtherSword": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Melee/DualShortSword/DualHeatSwords": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Melee/Axe/DualInfestedAxesWeapon": "Dojo Bio Lab",
  "/Lotus/Weapons/Tenno/Melee/DualKamas/DualKamas": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/Melee/Swords/QuillSword/QuillDualSwords": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/Melee/Soma/SomaDualKamas": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Melee/DualShortSword/DualShortSword": "Market Blueprint",
  "/Lotus/Weapons/Infested/Pistols/InfVomitGun/InfVomitGunWep": "Dojo Bio Lab",
  "/Lotus/Weapons/Tenno/Melee/Axe/DualAxeWeapon": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Melee/Polearms/DaxDuviriPolearm/DaxDuviriPolearmWeapon": "Duviri Acrithis",
  "/Lotus/Weapons/Infested/Pistols/InfestedPistol": "Dojo Bio Lab",
  "/Lotus/Weapons/Tenno/Melee/Swords/ThreeLeaf/ThreeLeaf": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/Melee/DualDagger/DualEtherDagger": "Quest",
  "/Lotus/Weapons/Tenno/Melee/Scythe/EtherScytheWeapon": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Melee/LongSword/EtherSword": "Market Blueprint",
  "/Lotus/Weapons/Corpus/LongGuns/CrpShapeBlast/CrpShapeBlastShotgun": "Market Blueprint",
  "/Lotus/Weapons/Corpus/Melee/Glaive/CrpGlaive/CrpGlaive": "Dojo Energy Lab",
  "/Lotus/Weapons/Tenno/Melee/DualDagger/DualDagger": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Zariman/LongGuns/PumpShotgun/ZarimanPumpShotgun": "Zariman Cavalero",
  "/Lotus/Weapons/Corpus/LongGuns/Spears/Railgun/CorpusRailgun": "Dojo Energy Lab",
  "/Lotus/Weapons/Tenno/Archwing/Primary/RocketArtillery/ArchRocketCrossbow": "Market Blueprint",
  "/Lotus/Weapons/ClanTech/Energy/CrpLaserRifle": "Dojo Energy Lab",
  "/Lotus/Weapons/Tenno/Melee/Hammer/HammerWeapon": "Market Blueprint",
  "/Lotus/Weapons/Tenno/LongGuns/TnWispRifle/TnWispRifle": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Melee/Fist/Fist": "Market Credits",
  "/Lotus/Weapons/Tenno/Pistol/AutoPistol": "Market Credits",
  "/Lotus/Weapons/Tenno/ThrowingWeapons/GlassKunai/GlassKunaiWeapon": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/Melee/Swords/GreatSword/TennoGreatSword": "Market Blueprint",
  "/Lotus/Weapons/Corpus/Melee/Whips/CrpShockGrip/CrpShockGripWhipWeapon": "Market Blueprint",
  "/Lotus/Weapons/Syndicates/CephalonSuda/Pistols/CSDroidArray": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Melee/PersianMachete/DjinnMachete": "Dojo Tenno Lab",
  "/Lotus/Weapons/Grineer/Melee/GrnGhoulSaw/GrnGhoulSawPlayer": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Melee/Glaives/LightGlaive/LightGlaiveWeapon": "Nightwave",
  "/Lotus/Weapons/Corpus/LongGuns/CrpFreezeRay/CrpFreezeRayRifle": "Dojo Energy Lab",
  "/Lotus/Weapons/Grineer/LongGuns/GrineerAssaultRifle/GrnAssaultRifle": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Melee/GreatSword/GreatSword": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Archwing/Primary/RepurposedGrineerAntiAircraftGun/ArchGRNAAGun": "Dojo Chem Lab",
  "/Lotus/Weapons/Grineer/LongGuns/GrineerLeverActionRifle/GLARifle": "Dojo Chem Lab",
  "/Lotus/Weapons/Tenno/Melee/Polearms/TnGuandaoPolearm/TnGuandaoPolearmWeapon": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/Melee/Warfan/WarfanWeapon": "Dojo Tenno Lab",
  "/Lotus/Weapons/Grineer/Melee/GrnBoomerang/GrnBoomerang": "Market Blueprint",
  "/Lotus/Weapons/Grineer/LongGuns/GrnHarpoonGun/GrnHarpoonGun": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Melee/Dagger/Dagger": "Nightwave",
  "/Lotus/Weapons/Tenno/Melee/Swords/HeatSword/HeatLongSword": "Nightwave",
  "/Lotus/Weapons/Tenno/Shotgun/QuadShotgun": "Market Blueprint",
  "/Lotus/Weapons/Cephalon/Melee/Hammer/CephHammerWeapon": "Dojo Energy Lab",
  "/Lotus/Weapons/Infested/LongGuns/InfWFAccompanyingPri/InfestedBurstRifle": "Dojo Bio Lab",
  "/Lotus/Weapons/Tenno/ThrowingWeapons/TennoStars": "Market Blueprint",
  "/Lotus/Weapons/Grineer/LongGuns/BurstRifle/GrnBurstRifle": "Market Blueprint",
  "/Lotus/Weapons/Infested/Melee/InfWFAccompanyingSparring/InfestedKogake": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Pistols/QuillDartgun/QuillDartGunWeapon": "Market Blueprint",
  "/Lotus/Weapons/ClanTech/Chemical/FlameThrower": "Dojo Chem Lab",
  "/Lotus/Weapons/ClanTech/Chemical/FlameThrowerWraith": "Dojo Chem Lab",
  "/Lotus/Weapons/Tenno/Zariman/Melee/Dagger/ZarimanDaggerWeapon": "Zariman Cavalero",
  "/Lotus/Weapons/Grineer/Melee/GrineerJetPoweredPolearm/GrineerJetPolearm": "Dojo Chem Lab",
  "/Lotus/Weapons/Grineer/Melee/GrnKusarigama/GrnKusarigamaWeapon": "Dojo Chem Lab",
  "/Lotus/Weapons/Grineer/LongGuns/GrnFlameSpear/GrnFlameSpear": "Dojo Chem Lab",
  "/Lotus/Weapons/Tenno/Melee/Swords/JawSword/JawLongSword": "Nightwave",
  "/Lotus/Weapons/Tenno/Melee/DualKamas/SingleKama": "Market Blueprint",
  "/Lotus/Weapons/Grineer/LongGuns/GrineerM16Homage/GrineerM16Rifle": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Melee/Swords/KrisDagger/KrisDagger": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/Archwing/Melee/ArchScythe/ArchScythe": "Market Blueprint",
  "/Lotus/Weapons/Grineer/Melee/GrineerHalberd/GrnHalberd": "Dojo Chem Lab",
  "/Lotus/Weapons/Tenno/Melee/Glaives/Boomerang/BoomerangWeapon": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/Pistols/TnPriestPistolScope/TnPriestPistolWeapon": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/Archwing/Melee/GrnArchHand/GrnArchHandWeapon": "Dojo Chem Lab",
  "/Lotus/Weapons/Tenno/Melee/BrassKnuckles/BrassKnuckles": "Market Blueprint",
  "/Lotus/Weapons/Grineer/LongGuns/GrnSpark/GrnSparkRifle": "Market Blueprint",
  "/Lotus/Weapons/Grineer/Pistols/GrnKohmPistol/GrnKohmPistol": "Dojo Chem Lab",
  "/Lotus/Weapons/Corpus/LongGuns/CrpSentAmlgSniper/CrpSentAmlgSniper": "Dojo Energy Lab",
  "/Lotus/Weapons/Tenno/Pistols/TnYareliPistol/TnYareliPistolWeapon": "Dojo Bash Lab",
  "/Lotus/Weapons/Grineer/GrineerPistol/GrnHeavyPistol": "Market Blueprint",
  "/Lotus/Weapons/Corpus/Melee/CrpVenusHatchet/CrpVenusHatchet": "Dojo Energy Lab",
  "/Lotus/Weapons/Grineer/Melee/GrnEgyptSwd/GrnEgyptSwdWeapon": "Dojo Chem Lab",
  "/Lotus/Weapons/Tenno/Melee/Tonfa/TonfaContestWinner/TennoTonfa": "Dojo Tenno Lab",
  "/Lotus/Weapons/Grineer/Pistols/GrnTorpedoPistol/GrnTorpedoPistol": "Market Blueprint",
  "/Lotus/Weapons/Tenno/ThrowingWeapons/Kunai": "Market Credits",
  "/Lotus/Weapons/Tenno/Melee/Swords/StalkerMios/StalkerMios": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/Zariman/Pistols/HeavyPistol/ZarimanHeavyPistol": "Zariman Cavalero",
  "/Lotus/Weapons/ClanTech/Energy/Railgun": "Dojo Energy Lab",
  "/Lotus/Weapons/Tenno/Archwing/Primary/TnShieldframeArchGun/TnShieldFrameArchGun": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Pistol/Pistol": "Market Credits",
  "/Lotus/Weapons/Tenno/Pistol/LatoPrime": "Founder Pack",
  "/Lotus/Weapons/Tenno/Rifle/SemiAutoRifle": "Market Blueprint",
  "/Lotus/Weapons/Corpus/Melee/Whip/CorpusWhipWeapon": "Market Blueprint",
  "/Lotus/Weapons/Corpus/Bow/Longbow/CrpBow": "Dojo Energy Lab",
  "/Lotus/Weapons/Infested/Melee/TipedoStaff/InfTipedoStaff": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Pistol/HeavyPistol": "Market Credits",
  "/Lotus/Weapons/Tenno/Melee/Maces/PaladinMace/PaladinMaceWeapon": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Pistols/Magnum/Magnum": "Market Blueprint",
  "/Lotus/Weapons/Grineer/Pistols/GrineerLeverActionPistol/GLAPistol": "Dojo Chem Lab",
  "/Lotus/Weapons/Tenno/Melee/Swords/TnChiselKanabo/TnChiselKanabo": "Market Blueprint",
  "/Lotus/Weapons/Infested/Melee/Swords/Mios/Mios": "Dojo Bio Lab",
  "/Lotus/Weapons/Infested/Melee/Swords/Mire/MireSword": "Market Blueprint",
  "/Lotus/Weapons/Grineer/LongGuns/GrineerSawbladeGun/SawBladeGun": "Boss Ceres Drop",
  "/Lotus/Weapons/MK1Series/MK1Bo": "Market Credits",
  "/Lotus/Weapons/Tenno/Rifle/StartingRifle": "Market Credits",
  "/Lotus/Weapons/MK1Series/MK1Furax": "Market Credits",
  "/Lotus/Weapons/MK1Series/MK1Furis": "Market Credits",
  "/Lotus/Weapons/MK1Series/MK1Kunai": "Market Credits",
  "/Lotus/Weapons/MK1Series/MK1Paris": "Market Credits",
  "/Lotus/Weapons/MK1Series/MK1Strun": "Market Credits",
  "/Lotus/Weapons/Infested/Bow/InfCernosBow/InfCernos": "Market Blueprint",
  "/Lotus/Weapons/Infested/LongGuns/InfCrpShockSwarm/InfCrpShockSwarmRifle": "Dojo Bio Lab",
  "/Lotus/Weapons/Tenno/LongGuns/GarudaCrossbow/GarudaCrossbow": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Melee/Swords/CutlassAndPoignard/CutlassPoignardSwords": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Melee/Swords/CutlassAndPoignard/TennoCutlass": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Bows/Omicrus/OmicrusPlayerWep": "Quest",
  "/Lotus/Weapons/Tenno/Melee/Swords/KatanaAndWakizashi/Katana": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/Melee/Nunchaku/Nunchaku/Nunchaku": "Dojo Tenno Lab",
  "/Lotus/Weapons/Grineer/Pistols/GrineerMicrowavegun/GrnMicrowavePistol": "Dojo Chem Lab",
  "/Lotus/Weapons/Corpus/Melee/KickAndPunch/KickPunchWeapon": "Dojo Energy Lab",
  "/Lotus/Weapons/Corpus/Pistols/CrpSentExperimentPistol/CrpSentExperimentPistol": "Dojo Energy Lab",
  "/Lotus/Weapons/ClanTech/Chemical/RocketLauncher": "Dojo Chem Lab",
  "/Lotus/Weapons/Corpus/Melee/CrpTonfa/CrpTonfa": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Melee/Swords/TennoSai/TennoSais": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/Archwing/Melee/Archaxe/ArchAxeWeapon": "Market Blueprint",
  "/Lotus/Weapons/Corpus/LongGuns/CrpBFG/CrpBFG": "Dojo Energy Lab",
  "/Lotus/Weapons/Tenno/Melee/Polearms/PolearmWeapon": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Melee/Glaives/TeshinGlaive/TnTeshinGlaiveWep": "Quest",
  "/Lotus/Weapons/Tenno/Pistols/TnBardPistol/TnBardPistolGun": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/Melee/Swords/PangolinSword/PangolinLongSword": "Nightwave",
  "/Lotus/Weapons/Tenno/LongGuns/Miter/TnoMiter": "Market Blueprint",
  "/Lotus/Weapons/Infested/LongGuns/QuantaFullyInfested/InfQuantaRifle": "Dojo Bio Lab",
  "/Lotus/Weapons/Tenno/Bows/HuntingBow": "Market Blueprint",
  "/Lotus/Weapons/Corpus/LongGuns/GrenadeLauncher/GrenadeLauncher": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Archwing/Primary/ArchLongRifle/ArchLongRifle": "Market Blueprint",
  "/Lotus/Weapons/Infested/LongGuns/Tentacluster/InfestedShotgun": "Dojo Bio Lab",
  "/Lotus/Weapons/Tenno/LongGuns/RevenantShotgun/RevenantShotgun": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Zariman/LongGuns/SemiAutoRifle/ZarimanSemiAutoRifle": "Zariman Cavalero",
  "/Lotus/Weapons/Tenno/Melee/Swords/PlasmaSword/PlasmaLongSword": "Nightwave",
  "/Lotus/Weapons/Corpus/Pistols/CrpSonificBlastor/CrpBlastorWeapon": "Market Blueprint",
  "/Lotus/Weapons/Infested/Pistols/InfProximityStars/InfProximityStars": "Dojo Bio Lab",
  "/Lotus/Weapons/Tenno/Zariman/Melee/Tonfas/ZarimanTonfaWeapon": "Zariman Cavalero",
  "/Lotus/Weapons/Tenno/Archwing/Primary/ArchwingHeavyPistols/Prisma/PrismaArchHeavyPistols": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Bows/PrimeDerelictCernos/DerelictCernos": "Market Blueprint",
  "/Lotus/Weapons/ClanTech/Energy/ElectroProd": "Dojo Energy Lab",
  "/Lotus/Weapons/ClanTech/Energy/VandalElectroProd": "Dojo Energy Lab",
  "/Lotus/Weapons/Infested/Melee/Nunchaku/InfNunchuck/InfNunchuck": "Market Blueprint",
  "/Lotus/Weapons/Infested/Melee/Staff/InfStaff/InfStaff": "Dojo Bio Lab",
  "/Lotus/Weapons/Tenno/Pistols/SawnOffShotgun/TennoHandShotgun": "Dojo Tenno Lab",
  "/Lotus/Weapons/Corpus/LongGuns/CrpShockRifle/CrpShockRifle": "Dojo Energy Lab",
  "/Lotus/Weapons/Grineer/LongGuns/GrnFourBarrelRifle/GrnFourBarrelRifleWeapon": "Dojo Chem Lab",
  "/Lotus/Weapons/Grineer/Pistols/GrnAmphisPistol/GrnAmphisPistol": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Archwing/Melee/ArchHammer/ArchHammer": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Melee/Gunblade/TnoGunblade": "Dojo Tenno Lab",
  "/Lotus/Weapons/Grineer/Melee/GrineerClaws/GrnClaws": "Market Blueprint",
  "/Lotus/Weapons/Tenno/LongGuns/FiveShotSniper/FiveShotSniper": "Market Blueprint",
  "/Lotus/Weapons/Operator/Melee/DrifterTazer/DrifterTazerPlayerWep": "Quest",
  "/Lotus/Weapons/Tenno/Melee/Hammer/DaxDuviriHammer/DaxDuviriHammerWeapon": "Duviri Acrithis",
  "/Lotus/Weapons/Tenno/Melee/Gunblade/GunbladeAutomatic/TnoGunbladeAutomatic": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/Melee/Axe/AxeWeapon": "Market Blueprint",
  "/Lotus/Weapons/Infested/Melee/Whip/InfestedWhip/InfestedWhipWeapon": "Dojo Bio Lab",
  "/Lotus/Weapons/Tenno/LongGuns/TnPriestSpear/TnPriestSpearGun": "Dojo Tenno Lab",
  "/Lotus/Weapons/Grineer/GrineerPistol/GrnScopedPistolPlayer": "Boss Vor Drop",
  "/Lotus/Weapons/Corpus/Melee/Polearm/CorpusPolearm01/CorpusPolearmWeapon": "Dojo Energy Lab",
  "/Lotus/Weapons/Tenno/Melee/Nunchaku/TnoNunchaku/TnoNunchaku": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/Melee/Hammer/IceHammer/IceHammer": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Pistol/BurstPistol": "Market Credits",
  "/Lotus/Weapons/Tenno/Melee/SwordsAndBoards/SundialSwordBoard/SundialBoardSword": "Daily Login",
  "/Lotus/Weapons/Tenno/Melee/SwordsAndBoards/MeleeContestWinnerOne/TennoSwordShield": "Dojo Tenno Lab",
  "/Lotus/Weapons/Operator/Pistols/DrifterPistol/DrifterPistolPlayerWeapon": "Quest",
  "/Lotus/Weapons/Tenno/Melee/LongSword/LongSword": "Market Credits",
  "/Lotus/Weapons/Tenno/Melee/LongSword/SkanaPrime": "Founder Pack",
  "/Lotus/Weapons/Tenno/Shotgun/DoubleBarrelShotgun": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Rifle/TennoAR": "Market Blueprint",
  "/Lotus/Weapons/Corpus/Pistols/CrpAirPistol/CrpAirPistolArray": "Market Blueprint",
  "/Lotus/Weapons/ClanTech/Energy/CrpLaserPistol": "Dojo Energy Lab",
  "/Lotus/Weapons/Tenno/ThrowingWeapons/LiDagger/LiDagger": "Dojo Tenno Lab",
  "/Lotus/Weapons/Corpus/LongGuns/CrpRubanRifle/CrpRubanRifle": "Granum Void",
  "/Lotus/Weapons/Corpus/Pistols/CrpElectroMag/CrpElectroMag": "Dojo Energy Lab",
  "/Lotus/Weapons/Tenno/LongGuns/TennoTommyGun/TennoTommyGunRifle": "Market Blueprint",
  "/Lotus/Weapons/Corpus/Melee/Gunblade/CrpGunBlade/CrpGunbladeWeapon": "Granum Void",
  "/Lotus/Weapons/Tenno/Shotgun/Shotgun": "Market Credits",
  "/Lotus/Weapons/Grineer/Pistols/GrnUzi/GrnUziWeapon": "Dojo Chem Lab",
  "/Lotus/Weapons/Grineer/Pistols/GrineerCrossbow/GrineerGooGun": "Market Blueprint",
  "/Lotus/Types/Friendly/PlayerControllable/Weapons/DuviriDualSwordsWeapon": "Duviri Acrithis",
  "/Lotus/Weapons/ClanTech/Energy/CrpHeavyRifle": "Dojo Energy Lab",
  "/Lotus/Weapons/Tenno/Melee/Swords/DaxDuviriKatana/DaxDuviriKatanaWeapon": "Duviri Acrithis",
  "/Lotus/Weapons/Tenno/LongGuns/TnoLeverAction/TnoLeverActionRifle": "Dojo Tenno Lab",
  "/Lotus/Weapons/Grineer/Melee/GrnTrident/GrnTridentWeapon": "Dojo Chem Lab",
  "/Lotus/Weapons/Infested/LongGuns/InfestedRifle": "Dojo Bio Lab",
  "/Lotus/Weapons/Tenno/ThrowingWeapons/U18ThrowingKnives/U18throwingknives": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/Melee/Swords/TnTwoHandedKatana/TnTwoHandedKatana": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Melee/Gauntlet/BrawlerKnuckles/BrawlerKnuckles": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/LongGuns/TnBardRifle/TnBardRifle": "Dojo Tenno Lab",
  "/Lotus/Weapons/Corpus/LongGuns/CorpusUMP/CorpusUMP": "Market Blueprint",
  "/Lotus/Weapons/Tenno/LongGuns/DrakeRifle/DrakeRifle": "Market Blueprint",
  "/Lotus/Weapons/Tenno/LongGuns/DoubleBarrelShotgun/TennoDoubleBarrelShotgun": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Melee/Staff/MonkSpade/TnoMonkStaff": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/Melee/Polearms/FlowerPowerPolearm/FlowerPowerPolearmWep": "Dojo Tenno Lab",
  "/Lotus/Weapons/Grineer/LongGuns/GrnGrenadeLauncher/GrnGrenadeLauncher": "Market Blueprint",
  "/Lotus/Weapons/ClanTech/Bio/BioWeapon": "Dojo Bio Lab",
  "/Lotus/Weapons/Thanotech/ThanoRifle/ThanotechRifle": "Deimos Father",
  "/Lotus/Weapons/Grineer/Melee/GrnDualFireAxe/GrnDualFireAxe": "Dojo Chem Lab",
  "/Lotus/Weapons/Grineer/LongGuns/GrineerAssaultRifle/TwinGrakatas": "Market Blueprint",
  "/Lotus/Weapons/Grineer/GrineerPistol/GrineerAkimboPistol": "Boss Ceres Drop",
  "/Lotus/Weapons/Grineer/Pistols/GrnDWUniques/GrnTwinKohmaks": "Dojo Chem Lab",
  "/Lotus/Weapons/Grineer/Melee/GrnEgyptSwd/DualGrnEgyptSwdWeapon": "Dojo Chem Lab",
  "/Lotus/Weapons/Grineer/Pistols/GrnQueenGuardDualPistol/GrnQueenGuardDualPistols": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Akimbo/AkimboViperPistols": "Market Blueprint",
  "/Lotus/Weapons/Infested/Pistols/InfestedDartPistol/InfestedDartPistol": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Pistol/RevolverPistol": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Rifle/TennoSniperRifle": "Market Blueprint",
  "/Lotus/Weapons/Tenno/LongGuns/TnRevolverRifle/TnRevolverRifleGun": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/Archwing/Primary/Railgun/ArchRailgun": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Pistols/TnOdaliskSmg/TnOdaliskSmgPistol": "Market Blueprint",
  "/Lotus/Weapons/Sentients/SentJointedScythe/SentJointedScytheWeapon": "Dojo Tenno Lab",
  "/Lotus/Weapons/Tenno/Melee/Claws/TennoClaws": "Dojo Tenno Lab",
  "/Lotus/Weapons/Grineer/GrineerPistol/GrineerLightPistol": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Melee/Hammer/GlassHammer/GlassHammer": "Market Blueprint",
  "/Lotus/Weapons/Grineer/LongGuns/GrineerSniperRifle/GrnSniperRifle": "Market Blueprint",
  "/Lotus/Weapons/Corpus/Melee/Glaive/CrpGhostCatcherGlaive/CrpGhostCatcherGlaive": "Quest",
  "/Lotus/Weapons/Tenno/Pistols/TnGuandoPistol/TnGuandoPistolGun": "Dojo Tenno Lab",
  "/Lotus/Weapons/Grineer/LongGuns/GrnCannon/GrnCannonWeapon": "Market Blueprint",
  "/Lotus/Weapons/Tenno/Melee/SunDialAxe/SundialAxeWeapon": "Daily Login",
  "/Lotus/Weapons/Tenno/LongGuns/LoginPrimary/SundialRifle": "Daily Login",
  "/Lotus/Weapons/Tenno/LongGuns/RepeatingCrossbow/RepeatingCrossbow": "Market Blueprint",
};
